import hashlib
import re


GENERATED_SIGNALS = [
    "this file was auto-generated", "do not edit",
    "auto generated", "generated by", "@generated",
]

LANG_EXTENSIONS = {
    "typescript": [".ts", ".mts", ".cts"],
}


def is_valid_code(code: str, lang: str) -> bool:
    if not code or len(code) < 150 or len(code) > 80_000:
        return False
    lines = [l for l in code.split("\n") if l.strip()]
    if len(lines) < 5:
        return False
    if sum(len(l) for l in lines) / len(lines) > 200:
        return False
    if sum(1 for c in code if ord(c) > 127) / len(code) > 0.15:
        return False
    if re.search(r'"resolved"\s*:\s*"https://', code):
        return False
    if any(s in code[:800].lower() for s in GENERATED_SIGNALS):
        return False
    if lang == "typescript":
        if not any(s in code for s in [
            "interface ", "type ", ": string", ": number", "=>",
            "async ", "await ", "export ", "import ",
        ]):
            return False
    return True


def dedup(samples: list[dict]) -> list[dict]:
    seen: set[str] = set()
    out = []
    for s in samples:
        h = hashlib.md5(s["content"].encode("utf-8", errors="ignore")).hexdigest()
        if h not in seen:
            seen.add(h)
            out.append(s)
    return out
